cache-size: 1000
mysql:
  user: username
  pass: password1
  dbname: mydatabase
  host: localhost
  port: 3306
  tableprefix: rpi_
playerinfo:
  # SimpleDateFormat: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  datetime-format: 'dd.MM.yyyy, HH:mm'
  datetime-zone: 'GMT+1'
  head: "\n&8------------------- [&6Player&fInfo&8] -------------------\n"
  info: "&6letzter Name: %playerprefix%%playernameaction%%playersuffix%\n&6UUID: %playeruuidaction%"
  status:
    online: "\n&6Status:\n  &2Online &f(seit %logintime% Uhr)"
    offline: "\n&6Status:\n  &4Offline &f(seit %logouttime% Uhr)"
    afk: "  &cafk, &7%afkreason% &f(seit %afktime% Uhr)"
    not-afk: "  &anicht afk"
  extra: "\n\n&c> %plots%\n&c> %head%\n&c> %moreinfo%\n "
  actions:
    playernameaction:
      text: '&7%playername%'
      click-event:
        action: 'run_command'
        value: '%playername%'
      hover-event:
        action: 'show_text'
        value: '&7Auswählen!'
    playeruuidaction:
      text: '&f%playeruuid%'
      click-event:
        action: 'run_command'
        value: '%playeruuid%'
      hover-event:
        action: 'show_text'
        value: '&7Auswählen!'
    plots:
      text: '&7Parzellen auflisten!'
      click-event:
        action: 'run_command'
        value: '/p list %sendername% %playername%'
      hover-event:
        action: 'show_text'
        value: '&7Befehl Auswählen!'
    head:
      text: '&7Kopf erhalten!'
      click-event:
        action: 'run_command'
        value: '/head %playername%'
      hover-event:
        action: 'show_text'
        value: '&7Befehl Auswählen!'
    moreinfo:
      text: '&7Weitere Informationen erhalten!'
      click-event:
        action: 'open_url'
        value: 'https://namemc.com/profile/%playeruuid%'
      hover-event:
        action: 'show_text'
        value: '&7https://namemc.com/profile/%playeruuid% öffnen!'
messages:
  public-broadcast: true
  is-afk: '&c[-] &f%player% &7ist gerade &fabwesend&7. %reason%'
  set-afk: '&7Du bist nun &fabwesend&7. %reason%'
  reason: '&8(%message%)'
  afk-with-no-reason: '-'
  no-afk: '&a[+] &f%player% &7ist wieder &fanwesend&7.'
  unset-afk: '&7Du bist nichtmehr &fabwesend&7.'
  auto-warning: '&8[&4Red&fAFK&8]&f: Bist du noch anwesend? &2Bewege dich kurz, damit der Server es erkennt!'
  auto-afk: 'Inaktiv'
  whos-afk: '&fAbwesend: &f%players%'
  noone-is-afk: '&fAbwesend: &f-'
  unknown-player:
    name: '&8[&6Player&fInfo&8]&f: &cDer angegebene Spieler "&4%input%&c" wurde &4nicht gefunden&c.'
    uuid: '&8[&6Player&fInfo&8]&f: &cDie angegebene Spieler-ID "&4%input%&c" wurde &4nicht gefunden&c.'
auto-afk:
  enabled: true
  time: 180
auto-warning:
  enabled: true
  time: 120
unset-manual-afk-on-activity: true